#!/bin/bash

lines=$(transmission-remote -l 2>/dev/null)
check=$(echo "$lines" | head -n 1 | awk '{ print $1 }')

if [ "$check" != "ID" ]; then
  exit
fi

lines=$(echo "$lines" | tail -n +2 | head -n -1)
count=0
done=0
out=""

IFS='
'
for x in $lines; do
  # ID,Done,Have,ETA,Up,Down,Ratio,Status,Name
  percent=$(echo $x | awk '{ print $2 }')
  status=""

  if [[ "$x" == *"Up & Down"* ]]; then
    status="↑↓"
  elif [[ "$x" == *"Down"* ]]; then
    status="↓"
  elif [[ "$x" == *"Up"* ]]; then
    status="↑"
  elif [[ "$x" == *"Stopped"* ]]; then
    status="-"
  fi

  if [ ! -z "$out" ]; then
    out="$out "
  fi

  out="$out$percent$status"
done

echo "$out"
