#!/bin/bash

. $(dirname "$0")/colors

DIR="${BLOCK_INSTANCE:-$HOME}"
ALERT_LOW="${1:-10}"

line=$(df -h -P -l "$DIR" | sed '1d')
IFS=' ' read -a tokens <<< "$line"

total="${tokens[1]}"
used="${tokens[2]}"
percent="${tokens[4]}"
percent="${percent//%}"

if [ $percent -gt 90 ]; then
  echo $(warnColor "$DIR:$used/$total")
else
  echo $(okColor "$DIR:$used/$total")
fi
