#!/bin/bash

lines=$(transmission-remote -l)
check=$(echo "$lines" | head -n 1 | awk '{ print $1 }')

if [ "$check" != "ID" ]; then
  exit
fi

lines=$(echo "$lines" | tail -n +2 | head -n -1)
warnColor="#b48ead"
count=0
done=0
out=""

IFS='
'
for x in $lines; do
  count=$((count + 1))

  # ID,Done,Have,ETA,Up,Down,Ratio,Status,Name
  percent=$(echo $x | awk '{ print $2 }')
  status=""
  warn=0

  if [[ "$x" == *"Up & Down"* ]]; then
    status="↑↓"
  elif [[ "$x" == *"Down"* ]]; then
    status="↓"
  elif [[ "$x" == *"Up"* ]]; then
    status="↑"
  elif [[ "$x" == *"Stopped"* ]]; then
    warn=1
  fi

  if [ "$percent" == "100%" ]; then
    done=$((done + 1))
    warn=1
  fi

  if [ $warn == 1 ]; then
    out="$out <span color='$warnColor'>$percent$status</span>"
  else
    out="$out $percent$status"
  fi
done

if [ $count -eq 0 ]; then
  exit
fi

echo "$out"
echo "$done/$count"
