#!/bin/bash

. $(dirname "$0")/colors

lines=$(transmission-remote -l)
check=$(echo "$lines" | head -n 1 | awk '{ print $1 }')

if [ "$check" != "ID" ]; then
  exit
fi

lines=$(echo "$lines" | tail -n +2 | head -n -1)
count=0
done=0
out=""

IFS='
'
for x in $lines; do
  # ID,Done,Have,ETA,Up,Down,Ratio,Status,Name
  percent=$(echo $x | awk '{ print $2 }')
  count=$((count + 1))

  if [ "$percent" == "100%" ]; then
    done=$((done + 1))
    out="$out $(okColor $percent)"
  elif [[ "$x" == *"Up & Down"* ]]; then
    out="$out $percent↑↓"
  elif [[ "$x" == *"Down"* ]]; then
    out="$out $percent↓"
  elif [[ "$x" == *"Up"* ]]; then
    out="$out $percent↑"
  elif [[ "$x" == *"Stopped"* ]]; then
    out="$out $(warnColor "$percent [stopped]")"
  elif [[ "$x" == *"Idle"* ]]; then
    out="$out $(criticalColor "$percent [idle]")"
  fi
done

if [ $count -eq 0 ]; then
  exit
fi

echo "$out"
echo "$done/$count"
